#!/usr/bin/env python
import atexit
import gobject
import logging
from dbus.mainloop.glib import DBusGMainLoop
from roberta.lab import Service

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger('roberta')

gobject.threads_init()
service = None


def cleanup():
    global service

    if service:
        service.hal.clearDisplay()
        service.hal.stopAllMotors()
        service.switchToTxtMode()
    logger.info('--- done ---')
    logging.shutdown()


def main():
    global service

    logger.info('--- starting ---')

    atexit.register(cleanup)

    DBusGMainLoop(set_as_default=True)
    loop = gobject.MainLoop()
    service = Service('/org/openroberta/Lab1')
    logger.debug('loop running')
    loop.run()

if __name__ == "__main__":
    main()
