#!/usr/bin/env python3
import atexit
import logging
import os
import sys

from gi.repository import GLib
from dbus.mainloop.glib import DBusGMainLoop

# prefer the module updated from the server
# the regular place where pip3 would install then would be
# ~/.local/lib/python3.7/site-packages
local_pkg_path = os.path.expanduser('~/.local/lib/python')
os.makedirs(local_pkg_path, exist_ok=True)
sys.path.insert(0, local_pkg_path)
from roberta.lab import Service

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger('roberta')

service = None


def cleanup():
    global service

    if service:
        service.hal.clearDisplay()
        service.hal.stopAllMotors()
        service.switchToTxtMode()
    logger.info('--- done ---')
    logging.shutdown()


def main():
    global service

    logger.info('--- starting ---')

    atexit.register(cleanup)

    DBusGMainLoop(set_as_default=True)
    loop = GLib.MainLoop()
    service = Service('/org/openroberta/Lab1')
    logger.debug('loop running')
    loop.run()


if __name__ == "__main__":
    main()
